version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci  # or 'npm install' if you prefer

    build:
      commands:
        - echo "Building Next.js project..."
        - npm run build
        - echo "Exporting static site..."
        - npm run export


artifacts:
  files:
    - '**/*'
  base-directory: out
  discard-paths: no