version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "🔧 Installing dependencies..."
      - npm ci
      - echo "✅ Installed dependencies"

  build:
    commands:
      - echo "⚙️ Building Next.js project..."
      - npm run build


  post_build:
    commands:
      - echo "📁 Verifying output folder"
      - ls -la
      - ls -la dist || (echo "❌ 'out' folder not found. Export failed." && exit 1)
      - echo "🚀 Uploading to S3..."
      - echo "✅ Deployment complete"

artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: yes
