version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci  # or 'npm install' if you prefer

  build:
    commands:
      - echo "Building Next.js project..."
      - npm run build
      - echo "Exporting static site..."
      - npm run export

  post_build:
    commands:
      - echo "Post-build: listing output folder"
      - ls -la
      - ls -la out || echo "❌ 'out' folder not found"
      - ls -la .next || echo "❌ '.next' folder not found"

artifacts:
  files:
    - '**/*'
  base-directory: out
  discard-paths: yes
